---
- hosts: localhost
  vars_files:
    - './secrets/users.yml'
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root

  tasks:
  - name: ensure apache is at the latest version
    apt:
      name: apache2
      state: latest
      #notify: "restart apache"

  - name: print hello world
    shell: echo "Hello World!"

  - name: ensure apache is running
    service:
      name: apache2
      state: started

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
        #listen: "restart apache"
