---
- hosts: vps
  remote_user: root
  become: true
  gather_facts: no
  pre_tasks:
    - name: apt update
      raw: 'sudo apt-get update'
    - name: install python 2.7 as python
      raw: 'sudo apt-get install -y python'

