---
- src: zzet.rbenv
  version: '3.3.1'
- src: haelle.certbot_ansible
  version: '1.2.0'
- src: haelle.calibre_web_ansible
  version: '1.4.0'
- src: geerlingguy.docker
  version: '2.9.0'
- src: haelle.vimrc
  version: 0.4.0
- src: haelle.oh_my_zsh
  version: 0.11.0
