---
- name: Install Munin master
  apt:
    name: munin
    state: installed

- name: Allow self inspection
  lineinfile:
    path: /etc/munin/munin-node.conf
    line: allow ^127.0.0.1$
    state: present
  notify:
    - restart munin-node

- name: add Munin tu UFW
  ufw:
    rule: allow
    port: 4949
    proto: tcp
    state: reloaded
  tags: ufw
