---
- name: User creation
  user:
    name: "{{ item.name }}"
    groups: sudo
    password: "{{ item.password if item.password is defined else '!' }}"
  with_items: "{{ users }}"

- name: Set authorized key for users
  authorized_key:
    user: '{{ item.name }}'
    state: present
    key: '{{ item.ssh_key }}'
  with_items: "{{ users }}"
  when: item.ssh_key is defined
