---
- name: passwordless sudo 1 of 2
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'

- name: passwordless sudo 2 of 2
  lineinfile:
    dest: /etc/sudoers
    state: absent
    line: '%sudo ALL=(ALL:ALL) ALL'
