---
- name: Create users
  include: create_users.yml
  tags: users

- name: Set root authorized key
  authorized_key:
    user: root
    state: present
    key: '{{ root_key }}'
  tags: users

- name: Disallow ssh password login
  include: disallow_ssh.yml
  tags: users
