---
- name: Install PHP
  include: php.yml
  tags:
    - php

- name: Install & configure MySQL
  include: mysql.yml
  tags:
    - mysql

- name: Download & install Wordpress
  include: wordpress.yml
  tags:
    - wordpress

- name: Nginx conf
  include: nginx_conf.yml
  tags:
    - nginx

- name: restart Nginx service
  service:
    name: nginx
    state: restarted
  tags:
    - nginx
