---
- name: Install ag
  apt:
    name: silversearcher-ag
    state: latest

- name: Copy agignore file for {{ user.name }}
  become_user: '{{ user.name }}'
  copy:
    src:    './files/agignore'
    dest:   '~/.agignore'
    mode:   '0644'

