---
- name: Install vim
  apt:
    name: vim
    state: present
  become: yes

# Need git and curl for vundle (vim plugin manager)
- name: Install Curl
  apt:
    name: curl
    state: present
  become: yes

- name: Install Vundle (vim plugin manager)
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: '~/.vim/bundle/vundle'
  become_user: "{{ user.name }}"

- name: Copy vimrc
  copy:
    src:  './files/vimrc'
    dest: '~/.vimrc'
    mode: '0644'
  become_user: "{{ user.name }}"

- name: Copy vimrc.bundles
  copy:
    src:  'vimrc.bundles'
    dest: '~/.vimrc.bundles'
    mode: '0644'
  become_user: "{{ user.name }}"

- name: Install vim plugins
  shell: vim +PluginInstall +qall
  become: yes
  become_user: "{{ user.name }}"
